export const statesWithCities = [
    { 
        state: "andhra pradesh", 
        cities: ["amaravati", "vijayawada", "visakhapatnam", "guntur", "nellore"]
    },
    { state: "arunachal pradesh", cities: ["itanagar", "tawang", "pasighat", "naharlagun", "tezu"] },
    { state: "assam", cities: ["dispur", "guwahati", "dibrugarh", "silchar", "jorhat"] },
    { state: "bihar", cities: ["patna", "muzaffarpur", "gaya", "bhagalpur", "darbhanga"] },
    { state: "chhattisgarh", cities: ["raipur", "bilaspur", "durg", "bhilai", "raigarh"] },
    { state: "goa", cities: ["panaji", "margao", "mapusa", "porvorim", "calangute"] },
    { state: "gujarat", cities: ["gandhinagar", "ahmedabad", "surat", "vadodara", "rajkot"] },
    { state: "haryana", cities: ["chandigarh", "gurugram", "faridabad", "panipat", "kurukshetra"] },
    { state: "himachal pradesh", cities: ["shimla", "manali", "dharmshala", "solan", "mandi"] },
    { state: "jharkhand", cities: ["ranchi", "jamshedpur", "dhanbad", "bokaro", "deoghar"] },
    { state: "karnataka", cities: ["bengaluru", "mysuru", "hubli", "mangaluru", "belagavi"] },
    { state: "kerala", cities: ["thiruvananthapuram", "kochi", "kollam", "thrissur", "kottayam"] },
    { state: "madhya pradesh", cities: ["bhopal", "indore", "gwalior", "jabalpur", "ujjain"] },
    { state: "maharashtra", cities: ["mumbai", "pune", "nagpur", "nashik", "aurangabad"] },
    { state: "manipur", cities: ["imphal", "churachandpur", "senapati", "thoubal", "bishnupur"] },
    { state: "meghalaya", cities: ["shillong", "tura", "nongsawlia", "jowai", "mahendraganj"] },
    { state: "mizoram", cities: ["aizawl", "lunglei", "serchhip", "saiha", "kolasib"] },
    { state: "nagaland", cities: ["kohima", "dimapur", "mokokchung", "tuensang", "mokokchung"] },
    { state: "odisha", cities: ["bhubaneswar", "cuttack", "rourkela", "berhampur", "puri"] },
    { state: "punjab", cities: ["chandigarh", "amritsar", "ludhiana", "jalandhar", "patiala"] },
    { state: "rajasthan", cities: ["jaipur", "jodhpur", "udaipur", "kota", "ajmer"] },
    { state: "sikkim", cities: ["gangtok", "namchi", "geyzing", "rangpo", "mungpoo"] },
    { state: "tamil nadu", cities: ["chennai", "coimbatore", "madurai", "tiruchirappalli", "salem"] },
    { state: "telangana", cities: ["hyderabad", "warangal", "nizamabad", "karimnagar", "khammam"] },
    { state: "tripura", cities: ["agartala"] },
    { state: "uttar pradesh", cities: ["lucknow", "kanpur", "varanasi", "agra", "noida"] },
    { state: "uttarakhand", cities: ["dehradun", "nainital", "haridwar", "mussoorie", "rudrapur"] },
    { state: "west bengal", cities: ["kolkata", "howrah", "siliguri", "durgapur", "asansol"] },
    { state: "delhi", cities: ["new delhi", "dwarka", "rohini", "karol bagh", "connaught place"] },
    { state: "andaman and nicobar islands", cities: ["port blair"] },
    { state: "chandigarh", cities: ["chandigarh"] },
    { state: "dadra and nagar haveli and daman and diu", cities: ["silvassa", "daman", "diu"] },
    { state: "lakshadweep", cities: ["kavaratti"] },
    { state: "puducherry", cities: ["puducherry", "karaikal", "mahe", "yanam"] },
    { state: "ladakh", cities: ["leh", "kargil"] }
];

export const stateArr=[
  "andhra pradesh",
  "arunachal pradesh",
  "assam",
  "bihar",
  "chhattisgarh",
  "goa",
  "gujarat",
  "haryana",
  "himachal pradesh",
  "jharkhand",
  "karnataka",
  "kerala",
  "madhya pradesh",
  "maharashtra",
  "manipur",
  "meghalaya",
  "mizoram",
  "nagaland",
  "odisha",
  "punjab",
  "rajasthan",
  "sikkim",
  "tamil nadu",
  "telangana",
  "tripura",
  "uttar pradesh",
  "uttarakhand",
  "west bengal",
  "delhi",
  "andaman and nicobar islands",
  "chandigarh",
  "dadra and nagar haveli and daman and diu",
  "lakshadweep",
  "puducherry",
  "ladakh"
]
